import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  trigger: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F8F8',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    paddingHorizontal: 12,
    height: 52,
    gap: 4,
  },
  flag: { fontSize: 20 },
  code: { fontSize: 14, fontWeight: '600', color: '#1D1D35' },
  chevron: { fontSize: 11, color: '#ADB5BD' },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '80%',
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 99,
    alignSelf: 'center',
    marginBottom: 16,
  },
  title: { fontSize: 17, fontWeight: '700', color: '#1D1D35', marginBottom: 12 },
  search: {
    backgroundColor: '#F7F8F8',
    borderRadius: 12,
    paddingHorizontal: 14,
    height: 44,
    fontSize: 14,
    color: '#1D1D35',
    marginBottom: 8,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F7F8F8',
    gap: 12,
  },
  itemFlag: { fontSize: 22, width: 32 },
  itemName: { flex: 1, fontSize: 14, color: '#1D1D35' },
  itemCode: { fontSize: 14, fontWeight: '600', color: '#92A3FD' },
});
