import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F4F5FA' },
  header: {
    backgroundColor: '#F4F5FA',
    paddingTop: 56,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  title: { fontSize: 26, fontWeight: '900', color: '#0F0F1A', letterSpacing: 0.5 },
  subtitle: { fontSize: 13, color: '#6B7280', marginTop: 4 },
  content: { flex: 1, paddingHorizontal: 20 },
  statsRow: { flexDirection: 'row', gap: 12, marginVertical: 16 },
  statCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  statIconBg: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: { fontSize: 24, fontWeight: '900', color: '#0F0F1A' },
  statLabel: { fontSize: 11, color: '#6B7280', marginTop: 2, fontWeight: '600' },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F0F1A',
    marginBottom: 10,
    marginTop: 4,
  },
  emptyState: { textAlign: 'center', color: '#6B7280', fontSize: 14, padding: 32 },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: '#7C3AED',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 8,
  },
  fabText: { color: '#fff', fontSize: 28, fontWeight: '300', marginTop: -2 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 28,
    paddingBottom: 40,
    maxHeight: '90%',
  },
  handle: {
    width: 44,
    height: 5,
    backgroundColor: '#E8ECF4',
    borderRadius: 99,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: { fontSize: 20, fontWeight: '800', color: '#0F0F1A', marginBottom: 20 },
  formLabel: { fontSize: 13, fontWeight: '700', color: '#0F0F1A', marginBottom: 10 },
  typeChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: '#E4E7F0',
  },
  typeChipActive: { backgroundColor: '#EDE9FE', borderColor: '#7C3AED' },
  typeChipText: { fontSize: 13, color: '#6B7280', fontWeight: '500' },
  typeChipTextActive: { color: '#7C3AED', fontWeight: '700' },
  recurrenceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  recChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E4E7F0',
  },
  recChipActive: { backgroundColor: '#EDE9FE', borderColor: '#7C3AED' },
  recChipText: { fontSize: 13, color: '#6B7280', fontWeight: '500' },
  recChipTextActive: { color: '#7C3AED', fontWeight: '700' },
  error: {
    color: '#FF6584',
    fontSize: 13,
    textAlign: 'center',
    backgroundColor: '#FFF0F4',
    padding: 10,
    borderRadius: 10,
  },
});
