import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F4F5FA' },
  header: {
    backgroundColor: '#F4F5FA',
    paddingTop: 56,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  title: { fontSize: 26, fontWeight: '900', color: '#0F0F1A', letterSpacing: 0.5 },
  subtitle: { fontSize: 13, color: '#6B7280', marginTop: 4 },
  content: { flex: 1, paddingHorizontal: 20 },
  filterRow: { flexDirection: 'row', marginVertical: 16 },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: '#E8ECF4',
  },
  filterChipActive: { backgroundColor: '#E0F7FA', borderColor: '#0891B2' },
  filterChipText: { fontSize: 13, color: '#6B7280', fontWeight: '500' },
  filterChipTextActive: { color: '#0891B2', fontWeight: '700' },
  chartCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  chartTitle: { fontSize: 15, fontWeight: '700', color: '#0F0F1A' },
  chartLatest: { fontSize: 22, fontWeight: '900', color: '#0891B2' },
  chartUnit: { fontSize: 12, color: '#9CA3AF' },
  listTitle: { fontSize: 16, fontWeight: '800', color: '#0F0F1A', marginBottom: 12 },
  emptyState: { textAlign: 'center', color: '#6B7280', fontSize: 14, padding: 32 },
  metricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  metricIconBg: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#EEF0FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  metricIcon: { fontSize: 20 },
  metricInfo: { flex: 1 },
  metricType: { fontSize: 14, fontWeight: '700', color: '#0F0F1A' },
  metricTime: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  metricValue: { fontSize: 16, fontWeight: '900', color: '#0891B2' },
  metricUnit: { fontSize: 11, color: '#9CA3AF' },
  deleteBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#FFF0F4',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  deleteBtnText: { color: '#FF6584', fontSize: 13, fontWeight: '700' },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: '#0891B2',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 8,
  },
  fabText: { color: '#fff', fontSize: 28, fontWeight: '300', marginTop: -2 },
});
