import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F4F6FC' },
  header: {
    backgroundColor: '#1A1A2E',
    paddingTop: 56,
    paddingBottom: 36,
    alignItems: 'center',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  avatarWrap: {
    width: 86,
    height: 86,
    borderRadius: 26,
    backgroundColor: '#6C63FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  avatarText: { fontSize: 36 },
  name: { fontSize: 20, fontWeight: '800', color: '#FFFFFF' },
  phone: { fontSize: 13, color: '#8898AA', marginTop: 4 },
  email: { fontSize: 13, color: '#8898AA', marginTop: 2 },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 8,
    backgroundColor: '#43D9AD20',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  verifiedText: { fontSize: 12, color: '#43D9AD', fontWeight: '700' },
  content: { flex: 1, paddingHorizontal: 20 },
  section: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    marginTop: 16,
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1A1A2E',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  msg: { fontSize: 13, textAlign: 'center', marginTop: 10, padding: 10, borderRadius: 12 },
  success: { backgroundColor: '#F0FFF8', color: '#43D9AD' },
  error: { backgroundColor: '#FFF0F4', color: '#FF6584' },
  emptyText: { fontSize: 13, color: '#8898AA', textAlign: 'center', paddingVertical: 8 },
  consentItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F4F6FC' },
  consentProvider: { fontSize: 14, fontWeight: '700', color: '#1A1A2E' },
  consentDetail: { fontSize: 12, color: '#8898AA', marginTop: 3 },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: '#FFF0F4',
    borderRadius: 14,
  },
  menuIconBg: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: '#FF658420',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  menuIcon: { fontSize: 18 },
  menuLabel: { flex: 1, fontSize: 14, fontWeight: '700', color: '#FF6584' },
  menuArrow: { fontSize: 18, color: '#FF6584' },
});
