import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    shadowColor: '#6C63FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconBg: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#EEF0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricLabel: { fontSize: 15, fontWeight: '700', color: '#1A1A2E' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  badge_active: { backgroundColor: '#EEF0FF' },
  badge_completed: { backgroundColor: '#F0FFF8' },
  badge_paused: { backgroundColor: '#FFF8EE' },
  badgeText: { fontSize: 11, fontWeight: '700' },
  badgeText_active: { color: '#6C63FF' },
  badgeText_completed: { color: '#43D9AD' },
  badgeText_paused: { color: '#FF9F43' },
  deleteBtn: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: '#FFF0F4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtnText: { color: '#FF6584', fontSize: 13, fontWeight: '700' },
  progressContainer: { marginBottom: 10 },
  progressBar: {
    height: 8,
    backgroundColor: '#F4F6FC',
    borderRadius: 99,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: { height: '100%', backgroundColor: '#6C63FF', borderRadius: 99 },
  progressLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  progressText: { fontSize: 12, color: '#8898AA' },
  progressPercent: { fontSize: 13, fontWeight: '800', color: '#6C63FF' },
  dates: { fontSize: 12, color: '#8898AA', marginTop: 4 },
} as any);
