import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E4E7F0',
    shadowColor: '#0891B2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconBg: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#E0F7FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricLabel: { fontSize: 15, fontWeight: '700', color: '#0F0F1A' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  badge_active: { backgroundColor: '#E0F7FA' },
  badge_completed: { backgroundColor: '#D1FAE5' },
  badge_paused: { backgroundColor: '#FEF3C7' },
  badgeText: { fontSize: 11, fontWeight: '700' },
  badgeText_active: { color: '#0891B2' },
  badgeText_completed: { color: '#10B981' },
  badgeText_paused: { color: '#D97706' },
  deleteBtn: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtnText: { color: '#F87171', fontSize: 13, fontWeight: '700' },
  progressContainer: { marginBottom: 10 },
  progressBar: {
    height: 8,
    backgroundColor: '#E4E7F0',
    borderRadius: 99,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: { height: '100%', backgroundColor: '#0891B2', borderRadius: 99 },
  progressLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  progressText: { fontSize: 12, color: '#9CA3AF' },
  progressPercent: { fontSize: 13, fontWeight: '800', color: '#0891B2' },
  dates: { fontSize: 12, color: '#9CA3AF', marginTop: 4 },
} as any);
